const validRequest = { "reservationDetails":
    { "id": 340,
      "sellRequestId": "QNdxfDJuUgSypUm50Ah5jQ==",
      "grossAmount": "44.31",
      "airlinePNR": "OCQYHA",
      "origin": "SFO",
      "gdsPNR": null,
      "email": "jgmisteli@gmail.com",
      "destination": "LAX",
      "orderID": "37B136932D2889230",
      "captureID": "38835580V4393605D",
      "created_at": "2019-08-29T09:02:02.397Z",
      "updated_at": "2019-08-29T09:02:39.409Z"},
   "passengerDetails":
    [ { "phoneNumber": "3127149869",
        "countryCode": "United States +1",
        "title": "Mr",
        "firstName": "Aurelien",
        "lastName": "Misteli",
        "nationalityCountry": "United States",
        "dateOfBirth": "2007-08-29T09:01:53.490Z",
        "passportNumber": "",
        "issueCountry": "United States",
        "passportExpiryDate": "2018-10-28T10:00:00.000Z",
        "type": "Adult",
        "email": "jgmisteli@gmail.com",
        "reservationDetail": null,
        "id": 75 } ],
   "flightDetails":
    [ { "id": 358,
        "flightID": "1890",
        "carrierId": "VX",
        "flightNum": "1890",
        "origin": "SFO",
        "destination": "LAX",
        "departureDateTime": "2018-04-23T05:50:00",
        "arrivalDateTime": "2018-04-23T07:22:00",
        "class": "N",
        "fareBasisCode": "",
        "validatingCarrier": "VX",
        "originAirportName": "San Francisco International Airport",
        "originAirportCity": "San Francisco",
        "originAirportCountry": "US",
        "destinationAirportName": "Los Angeles International Airport",
        "destinationAirportCity": "Los Angeles",
        "destinationAirportCountry": "US",
        "airlineName": "Virgin America",
        "majorClassCode": "Economy",
        "meal": null,
        "mile": null,
        "orgTerminal": "2",
        "destTerminal": "6",
        "carryOnBaggage": "0pieces",
        "duration": "92",
        "price": "44.31",
        "basePrice": "27.91" } ] }